[deploy]
bucket = 'cfn-project-artifact'
region = 'us-east-1'
stack_name = 'CruddurServiceBackendFlask'

[parameters]
EnvFrontendUrl = 'https://thecloudproject.store'
EnvBackendUrl = 'https://api.thecloudproject.store'
DDBMessageTable = 'CruddurDdb-DynamoDBTable-FPVY656UU87W'