[deploy]
bucket = 'cfn-project-artifact'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'aynfrancesco06/aws-bootcamp-cruddur-2023'
ArtifactBucketName = 'codepipeline-cruddur-artifact-cfn'
BuildSpec = 'backend-flask/buildspec.yml'